name: "Reintegrate fix"
on:
  pull_request:
    branches:
      - fix-**
    types: [ closed ]
jobs:
  reintegrate_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repo
        uses: actions/checkout@v2
