name: "Reintegrate fix"
on:
  pull_request:
    types: [ closed ]
jobs:
  reintegrate_branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'skip-reintegration') }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repo
        uses: actions/checkout@v2
